In [1]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
b = a ** 6
b.transpose()

array([[     1,   4096, 117649],
       [    64,  15625, 262144],
       [   729,  46656, 531441]], dtype=int32)

In [3]:
x = {'first': a, 'second': b}
x['second']

array([[     1,     64,    729],
       [  4096,  15625,  46656],
       [117649, 262144, 531441]], dtype=int32)

In [4]:
a[2,2] # old matlab nerves twitching...

9